### ISSUE TITLE
Add more information in Readme

### ISSUE THREAD

**Issue by sachin235** [sachin235/30Days-of-GCP#44]
Add brief details about GCP and both the tracks in the Readme.

**Comment by sunil14701** [comment]
hey please assign me this task . 
happy hacking

**Comment by jugshaurya** [comment]
@sunil14701, are you working on it?

**Comment by jugshaurya** [comment]
@sachin235, can i work on it?

**Comment by sachin235** [comment]
Yes sure @jugshaurya
