### ISSUE TITLE
Changes in Readme

### ISSUE THREAD

**Issue by sachin235** [sachin235/30Days-of-GCP#54]
- Remove the logo from the readme
- Provide link to the program website
- Remove the "why should I enroll" part as all these details can be viewed on the program website directly.

The aim of the repo is to help anyone trying to complete these labs for learning purposes, and not only specific to this 30 days program.

**Comment by Sajal193** [comment]
Hi @sachin235 , Can I work on this as a part of hacktoberfest 2021

**Comment by sachin235** [comment]
Sure @Sajal193

**Comment by sachin235** [comment]
Website is still not linked to the program website in the readme.

**Comment by Sajal193** [comment]
I have made a pull request. If any further changes are required, kindly suggest. Thank You
